### ISSUE TITLE
查看闹钟优化

### ISSUE THREAD

**Issue by YingLing3** [Zeta-qixi/nonebot-plugin-clock#1]
查看闹钟时，如果有@事件的闹钟，那么会直接艾特相关人员，建议改为纯文本

**Comment by Zeta-qixi** [comment]
已更新优化 ☑️

**Comment by YingLing3** [comment]
建议将查看闹钟指令触发改为on_regex，check = on_regex('^(查看闹钟|提醒事项|闹钟|⏰)$', block=True)
不然容易频繁触发

**Comment by Zeta-qixi** [comment]
☑️
