### ISSUE TITLE
删除闹钟建议

### ISSUE THREAD

**Issue by YingLing3** [Zeta-qixi/nonebot-plugin-clock#2]
![image](https://user-images.githubusercontent.com/44056856/231627543-4a3abe7d-2e4e-44a4-a66e-872538887564.png)

所有闹钟id通用，删除闹钟打错id，导致其他群的闹钟被删除，删除闹钟建议改为相互独立

**Comment by Zeta-qixi** [comment]
确实，修改为id和qq/群号联合检索
