### ISSUE TITLE
未设置每日闹钟，还是持续提醒

### ISSUE THREAD

**Issue by Mokouthebest** [Zeta-qixi/nonebot-plugin-clock#3]
昨天设置的单次闹钟，第二天还是继续提醒

![T{LM`0{MZN CIGP0TYSIY56](https://user-images.githubusercontent.com/32454843/231753068-8805bf79-7b3c-4bd8-80f4-38352fcfe685.png)
![4HG_{IE%J6A4P B{~SX9)MY](https://user-images.githubusercontent.com/32454843/231753080-7affb872-c985-4cb3-ab9e-e02760c27f92.png)
![4(ZW0~MKSX_6E0K6Q~CSGH](https://user-images.githubusercontent.com/32454843/231753089-17091224-073d-4804-b8b5-e057102203db.png)

**Comment by Mokouthebest** [comment]
而且无法查看闹钟 故而删除不了

**Comment by Zeta-qixi** [comment]
已修复，更新至 0.8.8 就ok了

**Comment by Mokouthebest** [comment]
好的
