### ISSUE TITLE
已经设置过一个闹钟后，无法再添加设置闹钟

### ISSUE THREAD

**Issue by Ayase-Naka-a** [Zeta-qixi/nonebot-plugin-clock#4]
没有配置黑白名单
CLOCK_WHITE_LIST = [qq_id1, qq_id2, ...] 
CLOCK_BLACK_LIST = [qq_id] 

已添加一个闹钟后，再也无法添加新的闹钟

插件版本：
![LNI4~VM2{9AMGYFI_D6B6KG](https://github.com/Zeta-qixi/nonebot-plugin-clock/assets/117055433/15857e85-c4c0-4943-80a1-29d41cb274f7)

报错信息：
![PS0ECY15M`%KBED88J8G~{Y](https://github.com/Zeta-qixi/nonebot-plugin-clock/assets/117055433/18fb7e87-f334-4d24-bc1c-3200c73918a9)

**Comment by Zeta-qixi** [comment]
修复了，更新至最新版本就行。如果还不行可以先把 【0】号的删除。

**Comment by Ayase-Naka-a** [comment]
删除插件再次安装，版本是0.8.8
验证bug并未修复，
bug复现步骤：
1.安装插件

pip install -U nonebot_plugin_clock

不设置黑白名单配置

2.在A群添加闹钟

设置闹钟 17:30 下班@A
回复
y

成功设置重复闹钟

3.在B群设置闹钟

设置闹钟 23:30 睡觉@B
回复
y

此时bot并不会回复闹钟添加成功

查看运行信息，报错如上图所示

**Comment by Ayase-Naka-a** [comment]
删除所有群闹钟，重复上述步骤，仍不能在两个群都设置重复闹钟

**Comment by Zeta-qixi** [comment]
新版本是0.9，看了一下是pypi目前不让做任何注册与更新。
修改 `/nonebot-plugin-clock/database` 72行
```
# return res[0][0] + 1 if res[0][0] else 0
# 修改为 -->
# return res[0][0] + 1 if res[0][0] else 1
```

**Comment by Zeta-qixi** [comment]
> 新版本是0.9，看了一下是pypi目前不让做任何注册与更新。 修改 `/nonebot-plugin-clock/database` 72行
> 
> ```
> # return res[0][0] + 1 if res[0][0] else 0
> # 修改为 -->
> # return res[0][0] + 1 if res[0][0] else 1
> ```

或者直接clone 仓库将`nonebot_plugin_clock` 放到对应的plugins目录下。

**Comment by Ayase-Naka-a** [comment]
按照上面进行代码修改后，
ok，已经可以正常设置了，
39
